# Generated by Django 6.0.4 on 2026-04-26 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_seed_demo_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='branch_shop',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
