# Generated by Django 6.0.4 on 2026-04-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_backfill_sale_subtotals'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.business'),
        ),
    ]
