# Generated by Django 6.0.4 on 2026-04-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_sale_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='gross_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
